config/routes.rb
PdmpSpike::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get "extension/medication" => "sections#medication_meta", as: "medication_meta"
  get "extension/demographic" => "sections#demographic_meta", as: "demographic_meta"

  get "people/:id/root" => "people#hdata_root", as: "hdata_root", :format => :xml

  get "people/:id/srpp" => "sections#srpp", as: "person_srpp_section"
  get "people/:id/srpp/report" => "sections#report", as: "person_report_doc"
  get "people/:id/srpp/demographic" => "sections#demographic", as: "person_demographic_doc"

  resources :people
  resources :prescriptions

  get "search/description" => "search#description", as: "description", :format => :opensearchdescription
  get "search" => "search#search", as: "searches"

  # land on the search page
  root :to => "search#search"

end

app/models/person.rb
require 'date'

class Person < ActiveRecord::Base
  validates :family_name, :presence => true
  validates :sex_id, :presence => true
  attr_accessible :title, :given_name, :family_name, :sex_id, :birthdate, :address_id, :address_attributes, :phone
  belongs_to :sex
  belongs_to :address
  has_many :prescriptions_received, :class_name => Prescription, :foreign_key => :patient_id
  has_many :prescriptions_written, :class_name => Prescription, :foreign_key => :prescriber_id
  has_many :fulfillments, :class_name => Fulfillment, :foreign_key => :pharmacist_id
  accepts_nested_attributes_for :address, :reject_if => :all_blank

  def name
    [title, given_name, family_name].select{|f| f.present?}.join " "
  end

  def self.search(search)
    if search
      where('people.family_name LIKE :q or people.given_name LIKE :q or addresses.street LIKE :q or addresses.city LIKE :q or addresses.state LIKE :q OR addresses.postal_code LIKE :q', :q => "%#{search}%").includes(:address)
    else
      find(:all)
    end
  end

  # expects a populated Search model
  def self.advanced_search(params)
    return [] unless params

    query_terms = []
    query_params = {}

    if params.given.present?
      query_terms << "people.given_name = :given"
      query_params[:given] = params.given
    end
    if params.family.present?
      query_terms << "people.family_name = :family"
      query_params[:family] = params.family
    end
    if params.gender.present?
      sex = Sex.find_by_display_name(params.gender.capitalize)
      query_terms << "people.sex_id = :sex"
      query_params[:sex] = sex.id
    end
    if params.loc.present?
      query_terms << "(addresses.street LIKE :loc or addresses.city LIKE :loc or addresses.state LIKE :loc OR addresses.postal_code LIKE :loc)"
      query_params[:loc] = "%#{params.loc}%"
    end
    if params.dob.present?
      # if the parameter is a String it needs to be parsed to a Date
      dob = params.dob.class == String && Date.parse(params.dob) || params.dob
      query_terms << "people.birthdate = :dob"
      query_params[:dob] = dob
    end

    query_params.present? and where(query_terms.join(" AND "), query_params).includes(:address)
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.atom
  def index
    @people = Person.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.atom { render template: "search/search" }
    end
  end

  def hdata_root
    @person = Person.find(params[:id])
  end

  # GET /people/1
  # GET /people/1.atom
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.atom
    end
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.address = Address.new
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])

    # if the person doesn't have an address then give the user a
    # chance to add one
    if !@person.address
      @person.address = Address.new
    end
  end

  # POST /people
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /people/1
  def update
    @person = Person.find(params[:id])

    # if all the address form parameters are empty then "disconnect"
    # the person from the address
    addr = params[:person][:address_attributes]
    if (addr && ""==addr[:street] && ""==addr[:city] && ""==addr[:state] && ""==addr[:postal_code])
      @person.address = nil
      params[:person].delete :address_attributes
    end

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /people/1
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
    end
  end

end

app/helpers/people_helper.rb
# -*- coding: utf-8 -*-
module PeopleHelper
  # this makes me sad, but I couldn't get builder to escape/unescape
  # the URL properly, so we have to do it in an ad-hoc way here
  def search_url_template
    "#{searches_url}?family={pdmp:familyname?}&amp;given={pdmp:givenname?}&amp;gender={pdmp:gender?}&amp;loc={pdmp:loc?}&amp;dob={pdmp:dob?}".to_sym
  end
end

app/views/people/_form.html.erb
<%= simple_form_for @person do |f| %>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= f.input :given_name %>
  <%= f.input :family_name %>
  <%= f.association :sex, label_method: :display_name %>
  <%= f.input :birthdate, :include_blank => true, :start_year => Date.today.year - 90, :end_year => Date.today.year - 12 %>
  <%= f.input :phone %>

  <%= f.simple_fields_for :address, @person.address do |a| %>
  <%= a.input :street %>
  <%= a.input :city %>
  <%= a.input :state, :collection => state_codes %>
  <%= a.input :postal_code %>
  <% end %>

  <%= f.button :wrapped, :cancel => people_path %>
<% end %>

app/views/people/_results.html.erb
<table class="table table-condensed">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Gender</th>
    <th>Birthdate</th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= link_to person.name, person %></td>
    <td><%= person.address %>
    <td><%= person.sex.try(:display_name) %>
    <td><%= person.birthdate %>
  </tr>
<% end %>
</table>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

app/views/people/index.html.erb
<div id="people_search" class="span4 pull-right">
<%= simple_form_for people_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil, :class => "btn" %>
<% end %>
</div>

<h1>People</h1>

<%= render "results" %>

<%= link_to new_person_path do %>
<i class="icon-plus"></i> New Person
<% end %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

app/views/people/show.html.erb
<p>
  <h1><%= @person.name %></h1>
  <b>Sex:</b>
  <%= @person.sex.display_name %><br/>
  <b>Birthdate:</b>
  <%= @person.birthdate %><br/>
<% if @person.address %>
  <b>Address:</b><%= @person.address %><br/>
<% end %>
<% if !@person.phone.blank? %>
  <b>Phone:</b> <%= @person.phone %><br/>
<% end %>
</p>

<% if @person.prescriptions_received.any? %>
<p><b>Prescriptions Received</b>
  <table class="table table-condensed">
    <tr>
      <th>Drug</th>
      <th>Prescriber</th>
      <th>When Written</th>
    </tr>

  <% @person.prescriptions_received.each do |rx| %>
  <tr>
    <td><%= rx.drug.name %></td>
    <td><%= rx.prescriber.name %></td>
    <td><%= rx.when_written %></td>
  </tr>
  <% end %>
  </table>
</p>
<% end %>

<% if @person.prescriptions_written.any? %>
<p><b>Prescriptions Written</b>
  <table class="table table-condensed">
    <tr>
      <th>Drug</th>
      <th>Patient</th>
      <th>When Written</th>
    </tr>

  <% @person.prescriptions_written.each do |rx| %>
  <tr>
    <td><%= rx.drug.name %></td>
    <td><%= rx.patient.name %></td>
    <td><%= rx.when_written %></td>
  </tr>
  <% end %>
  </table>
</p>
<% end %>

<% if @person.fulfillments.any? %>
<p><b>Fulfillments</b>
  <table class="table table-condensed">
    <tr>
      <th>Rx Number</th>
      <th>When Filled</th>
      <th>Pharmacy</th>
      <th>Prescription</th>
      <th>Quantity</th>
      <th>Status</th>
    </tr>

  <% @person.fulfillments.each do |fill| %>
  <tr>
    <td><%= fill.prescription_number %></td>
    <td><%= fill.when_filled %></td>
    <td><%= fill.pharmacy.name %></td>
    <td><%= link_to fill.prescription.id, prescription_path(fill.prescription) %></td>
    <td><%= fill.quantity_amount %> <%= fill.quantity_unit %></td>
    <td><%= fill.fill_status %></td>
  </tr>
  <% end %>
  </table>
</p>
<% end %>

<p>
<%= link_to edit_person_path(@person) do %>
<i class="icon-edit"></i> Edit
<% end %>
|
<%= link_to person_path(@person), method: :delete, data: { confirm: 'Are you sure?' } do %>
<i class="icon-remove"></i> Delete
<% end %>
</p>
<p>
<%= link_to people_path do %>
<i class="icon-chevron-up"></i> Back to People
<% end %>
</p>