config/routes.rb
PdmpSpike::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get "extension/medication" => "sections#medication_meta", as: "medication_meta"
  get "extension/demographic" => "sections#demographic_meta", as: "demographic_meta"

  get "people/:id/root" => "people#hdata_root", as: "hdata_root", :format => :xml

  get "people/:id/srpp" => "sections#srpp", as: "person_srpp_section"
  get "people/:id/srpp/report" => "sections#report", as: "person_report_doc"
  get "people/:id/srpp/demographic" => "sections#demographic", as: "person_demographic_doc"

  resources :people
  resources :prescriptions

  get "search/description" => "search#description", as: "description", :format => :opensearchdescription
  get "search" => "search#search", as: "searches"

  # land on the search page
  root :to => "search#search"

end

app/models/search.rb
class Search
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :given, :family, :gender, :loc, :dob, :attributes_provided
  alias_method :attributes_provided?, :attributes_provided

  def initialize(attributes = {})
    attributes.each do |name, value|
      begin
        send("#{name}=", value)
        self.attributes_provided = true
      rescue NoMethodError
      end
    end
  end

  def persisted?()    false  end
  def new_record?()   true   end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @search = Search.new(params)
    @people = Person.advanced_search(@search)

    flash.now[:alert] = "No Results Found" if @search.attributes_provided? && @people.blank?

    respond_to do |format|
      format.html
      format.atom
    end
  end

  def description
  end

end

app/views/search/search.html.erb
<h1>Search</h1>

<%= simple_form_for @search, :method => 'get' do |s| %>
  <%= s.input :given, label: "Given (First) Name", input_html: { name: "given" } %>
  <%= s.input :family, label: "Family (Last) Name", input_html: { name: "family" } %>
  <%= s.input :gender, label: "Gender", collection: Sex.all.map { |s| [s.display_name, s.display_name.downcase] }, include_blank: true, input_html: { name: "gender" } %>
  <%= s.input :loc, label: "Location", input_html: { name: "loc" } %>
  <%= s.input :dob, label: "Date of Birth", input_html: { name: "dob" } %>

  <%= s.button :wrapped, "Search", :cancel => searches_path %>
<% end %>

<% if @people.present? %>
<h2>Results</h2>
<%= render "people/results" %>
<% end %>