config/routes.rb
PdmpSpike::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get "extension/medication" => "sections#medication_meta", as: "medication_meta"
  get "extension/demographic" => "sections#demographic_meta", as: "demographic_meta"

  get "people/:id/root" => "people#hdata_root", as: "hdata_root", :format => :xml

  get "people/:id/srpp" => "sections#srpp", as: "person_srpp_section"
  get "people/:id/srpp/report" => "sections#report", as: "person_report_doc"
  get "people/:id/srpp/demographic" => "sections#demographic", as: "person_demographic_doc"

  resources :people
  resources :prescriptions

  get "search/description" => "search#description", as: "description", :format => :opensearchdescription
  get "search" => "search#search", as: "searches"

  # land on the search page
  root :to => "search#search"

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  validates :patient_id, :presence => true
  validates :prescriber_id, :presence => true
  validates :drug_id, :presence => true
  validates :order_number, :presence => true
  validates :quantity_amount, :presence => true
  validates :quantity_units, :presence => true
  validates :effective_start, :presence => true
  validates :effective_end, :presence => true
  attr_accessible :patient_id, :prescriber_id, :drug_id, :when_written, :expiration, :free_text_sig, :effective_start, :effective_end, :order_number, :fills_count, :quantity_amount, :quantity_units
  belongs_to :patient, :class_name => Person
  belongs_to :prescriber, :class_name => Person
  belongs_to :drug
  has_many :fulfillments
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  # GET /prescriptions
  def index
    @prescriptions = Prescription.all
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.xml
  def show
    @prescription = Prescription.find(params[:id])
  end

  # GET /prescriptions/new
  def new
    @prescription = Prescription.new
  end

  # GET /prescriptions/1/edit
  def edit
    @prescription = Prescription.find(params[:id])
  end

  # POST /prescriptions
  def create
    @prescription = Prescription.new(params[:prescription])

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /prescriptions/1
  def update
    @prescription = Prescription.find(params[:id])

    respond_to do |format|
      if @prescription.update_attributes(params[:prescription])
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /prescriptions/1
  def destroy
    @prescription = Prescription.find(params[:id])
    @prescription.destroy

    respond_to do |format|
      format.html { redirect_to prescriptions_url }
    end
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<%= simple_form_for @prescription do |f| %>
  <%= f.error_notification %>

    <%= f.input :patient_id, :collection => Person.all.collect {|p| [ p.name, p.id ] } %>
    <%= f.input :prescriber_id, :collection => Person.all.collect {|p| [ p.name, p.id ] } %>
    <%= f.input :drug_id, :collection => Drug.all.collect {|p| [ p.name, p.id ] } %>
    <%= f.input :when_written %>
    <%= f.button :wrapped, :cancel => prescriptions_path %>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing prescription</h1>

<%= render 'form' %>

app/views/prescriptions/index.html.erb
<h1>Prescriptions</h1>

<table class="table table-condensed">
  <tr>
    <th>Patient</th>
    <th>Prescriber</th>
    <th>Drug</th>
    <th>When written</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prescriptions.each do |prescription| %>
  <tr>
    <td><%= prescription.patient.name %></td>
    <td><%= prescription.prescriber.name %></td>
    <td><%= prescription.drug.name %></td>
    <td><%= prescription.when_written %></td>
    <td><%= link_to 'Show', prescription %></td>
    <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
    <td><%= link_to 'Destroy', prescription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prescription', new_prescription_path %>

app/views/prescriptions/new.html.erb
<h1>New prescription</h1>

<%= render 'form' %>

app/views/prescriptions/show.html.erb
<p>
  <b>Patient:</b>
  <%= @prescription.patient.name %>
</p>

<p>
  <b>Prescriber:</b>
  <%= @prescription.prescriber.name %>
</p>

<p>
  <b>Drug:</b>
  <%= @prescription.drug.name %>
</p>

<p>
  <b>When written:</b>
  <%= @prescription.when_written %>
</p>

<% if @prescription.fulfillments.any? %>
<p><b>Fulfillments</b>
  <table class="table table-condensed">
    <tr>
      <th>Rx Number</th>
      <th>When Filled</th>
      <th>Pharmacy</th>
      <th>Pharmacist</th>
      <th>Quantity</th>
      <th>Status</th>
    </tr>

  <% @prescription.fulfillments.each do |fill| %>
  <tr>
    <td><%= fill.prescription_number %></td>
    <td><%= fill.when_filled %></td>
    <td><%= fill.pharmacy.name %></td>
    <td><%= link_to fill.pharmacist.name, person_path(fill.pharmacist) %></td>
    <td><%= fill.quantity_amount %> <%= fill.quantity_unit %></td>
    <td><%= fill.fill_status %></td>
  </tr>
  <% end %>
  </table>
</p>
<% end %>

<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'Back', prescriptions_path %>