config/routes.rb
PdmpSpike::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get "extension/medication" => "sections#medication_meta", as: "medication_meta"
  get "extension/demographic" => "sections#demographic_meta", as: "demographic_meta"

  get "people/:id/root" => "people#hdata_root", as: "hdata_root", :format => :xml

  get "people/:id/srpp" => "sections#srpp", as: "person_srpp_section"
  get "people/:id/srpp/report" => "sections#report", as: "person_report_doc"
  get "people/:id/srpp/demographic" => "sections#demographic", as: "person_demographic_doc"

  resources :people
  resources :prescriptions

  get "search/description" => "search#description", as: "description", :format => :opensearchdescription
  get "search" => "search#search", as: "searches"

  # land on the search page
  root :to => "search#search"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDMP Spike</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="search"
        type="application/opensearchdescription+xml"
        href="<%= description_url %>"
        title="PDMP Patient Search" />
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <p class="navbar-text pull-right">
      <%= yield(:authn) %>
    </p>
    <a class="brand" href="/">PDMP Spike</a>
    <%= yield(:topnav) %>
  </div>
</div>

<% if flash[:notice] %>
<div class="container alert alert-success">
  <%= notice %>
  <button class="close" data-dismiss="alert" type="button">&#215;</button>
</div>
<% end %>
<% if flash[:alert] %>
<div class="container alert">
  <%= alert %>
  <button class="close" data-dismiss="alert" type="button">&#215;</button>
</div>
<% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/auth.html.erb
<% content_for :authn do %>
<%= current_user.email %> 
| 
<%= link_to destroy_user_session_path, :method => :delete do %>
<i class="icon-signout"></i> Sign out
<% end %>
<% end %>

<% content_for :topnav do %>
<%= render "topnav" %>
<% end %>

<%= render :file => 'layouts/application' %>

app/views/layouts/unauth.html.erb
<%= render :file => 'layouts/application' %>